repos:
-   repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    - id: black
      language_version: python3.8
-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
      language_version: python2.7
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0  # Use the ref you want to point at
    hooks:
    -   id: trailing-whitespace
        exclude: ^source/tests/chaos/chaos_loading.sql # Otherwise, Sql commands get corrupted
    -   id: check-ast
    -   id: check-merge-conflict
    -   id: check-yaml
        args: [--allow-multiple-documents]
-   repo: https://github.com/hove-io/navitia-pre-commit
    rev: ccf8608238538007c77983a0a03e617b7afa6011
    hooks:
    -   id: clang-format
        verbose: true
        exclude: ^source/third_party/
        files: \.(c|cc|cxx|cpp|h|hpp|hxx)$
        args: [-i]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.950
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports, --py2]
        files: source
        language_version: python3.8
        exclude: /monitor/|/third_party/|/tests/|/sql/|env\.py$|setup\.py$
