name: Build Navitia Packages For Release

on:
  push:
    branches:
      - release_


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
        matrix:
            distribution: [debian8, debian10, debian11]

    container:
      image: navitia/${{matrix.distribution}}_dev
      volumes:
          - /usr/share/dotnet:/usr/share/dotnet
          - /usr/local/lib/android:/usr/local/lib/android
        # Mount /dotnet so we can delete files from docker and free up space (>20GB)

    steps:
    - name: Free up space
      run: |
        rm -rf /usr/share/dotnet/*
        rm -rf /usr/local/lib/android/*
        echo "Free space:"
        df -h
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: install zip dependency
      run: apt update && apt install -y --force-yes zip httpie dh-python
    - name: dkpg-buildpackage
      run: |
        sed -i 's,git\@github.com:\([^/]*\)/\(.*\).git,https://github.com/\1/\2,' .gitmodules
        git submodule update --init --recursive
        DEB_BUILD_OPTIONS=nocheck dpkg-buildpackage -b
    - name: create navitia_${{matrix.distribution}}_packages.zip
      run: |
        zip navitia_${{matrix.distribution}}_packages.zip ../navitia-* ../mock-kraken*
    - name: upload ${{matrix.distribution}} packages
      uses: actions/upload-artifact@v3
      with:
        name: navitia-${{matrix.distribution}}-packages
        path: "navitia_${{matrix.distribution}}_packages.zip"
    - name: remove useless temporary files
      run: rm -rf ../navitia-*

    - name: slack notification (the job has failed)
      if: failure()
      run: |
          echo '{"text":":warning: Github Actions: build_navitia_packages_for_release failed ! (https://github.com/hove-io/navitia/actions?query=workflow%3A%22Build+Navitia+Packages+For+Release%22). Navboys, this is a release alert !!!"}' | http --json POST ${{secrets.SLACK_NAVITIA_TEAM_URL}}

    - name: notifications (the job has successed)
      if: success() && matrix.distribution == 'debian8'
      run: |
          version_number=$(head -n 1 debian/changelog | cut -d'(' -f 2 | cut -d')' -f 1)
          echo '{"text":":information_source: Navitia Github Actions: build_navitia_packages_for_release succeded -' $version_number 'navitia debian packages are available"}' | http --json POST ${{secrets.SLACK_NAVITIA_TEAM_URL}}
          echo '{"text":":octopus: Navitia Release: The version' $version_number 'is available. changelog: https://github.com/hove-io/navitia/releases/tag/v'$version_number'"}' | http --json POST ${{secrets.SLACK_NAVITIA_URL}}

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v5.2
    - uses: actions/checkout@v3
      with:
        repository: hove-io/navitia-docker-compose
    - name: install httpie dependency
      run: sudo apt update && sudo apt install -y httpie
    - uses: actions/download-artifact@v3 # Download all artifacts Debian8 (job 'build') to the current working directory
      with:
        name: navitia-debian8-packages
        path: ./builder_from_package
    - name: build, create and publish images for branch release
      working-directory: builder_from_package
      run: ./build.sh -o ${{secrets.access_token_github}} -d debian8 -n -r -e push -t latest -b release -u ${{secrets.docker_user}} -p ${{secrets.docker_password}}
    - name: slack notification (the job has failed)
      if: failure()
      run: |
          echo '{"text":":warning: Navitia Github Actions: publish_docker_compose_images failed ! "}' | http --json POST ${{secrets.SLACK_NAVITIA_TEAM_URL}}
