name: Build Navitia Dockers debian11

on:
    pull_request:
#  push:
#    branches:
#      - dev
#    tags:
#      - '*'

env:
  debian_version: debian11

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Free up space
      run: |
        sudo rm -rf /usr/share/dotnet/*
        sudo rm -rf /usr/local/lib/android/*
        echo "Free space:"
        df -h

    - name: Install dependencies
      run: |
        sudo apt update && sudo apt install -y --force-yes zip httpie

    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules : recursive
        fetch-depth: 0

    - name: Restore ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: build_dockers
        max-size: 2000M

    - name: Choose release tag
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        version=$(git describe --tags)
        echo "building version $version"
        echo "navitia_tag=${{env.debian_version}}_$version" >> $GITHUB_ENV

    - name: Create builder docker
      run: |
        docker build -f docker/${{env.debian_version}}/Dockerfile-builder -t navitia/builder .

    - name: Build navitia
      run: |
        docker run -v `pwd`:/navitia/navitia/  navitia/builder

    - name: Create navitia images
      run: |
        docker build -t navitia/jormungandr:debian11_test -f  docker/${{env.debian_version}}/Dockerfile-jormungandr .

    - name: Login dockerhub
      run: |
        docker login -u ${{secrets.docker_user}} -p ${{secrets.docker_password}}


    - name: Push navitia images
      run: |
        docker push navitia/jormungandr:debian11_test
