name: Clang-tidy

on:
  push:
    branches:
    - clang-tidy
    - release

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
    - name : Dump Github Context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo $GITHUB_CONTEXT

  clang-tidy:
    runs-on: ubuntu-latest
    container:
      image: navitia/debian11_dev
    steps:
    - uses: actions/checkout@v3
      with:
          submodules: 'recursive'
    - name : Install dependencies
      run: apt update && apt install -y clang-tools clang-tidy
    - name : Clang-tidy Info
      run: clang-tidy --version
    - name: cmake
      working-directory: ${{ runner.temp }}
      run: cmake $GITHUB_WORKSPACE/source
    - name: Clang-tidy
      working-directory: ${{ runner.temp }}
      run: make tidy_fix || echo "Files have been tidied ! Let's commit them"
    - name: Commit and push changes
      # Handle case with no clang-tidy fix
      continue-on-error: true
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Clang-tidy the code base
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        title: '[Clang-Tidy] Code maintenance and modernisation'
        body: |
          🤖 This is an automatic PR 🤖

          Clang-tidy suggests the following changes so far:
          - `clang-analyzer-*` : clang Static Analyzer checks.

          [#clang-tidy documentation](https://clang.llvm.org/extra/clang-tidy/)
        labels: not_in_changelog
        team-reviewers: hove-io/coreteam
        branch: auto/clang-tidy
        base: dev
    - name: Check outputs
      if: ${{ success() }}
      run: |
        echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"

