name: Publish Hove images on AWS

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build Navitia Packages For Release", "Build Navitia Packages For Dev Multi Distributions"]
    branches: [release, dev]
    types:
      - completed

jobs:
  aws_dev_images:
    runs-on: [self-hosted, deploy, sandbox]
    if: ${{ github.event.workflow_run.head_branch == 'dev' }}
    name: AWS Dev images
    steps:
      - name: Generate token
        id: app-token
        uses: getsentry/action-github-app-token@v1
        with:
          app_id: ${{ secrets.AWS_TERRAFORM_WORKFLOW_APP_ID }}
          private_key: ${{ secrets.AWS_TERRAFORM_WORKFLOW_APP_PEM_KEY }}

      - name: Checkout mimirsbrunn-config
        uses: actions/checkout@v3
        with:
          repository: hove-io/mimirsbrunn-config
          token: ${{ steps.app-token.outputs.token }}
          path: .mimirsbrunn-config

      - name: tyr-worker update
        run: |
          cat << EOF > .mimirsbrunn-config/Dockerfile
          FROM navitia/tyr-worker
          COPY ./config /etc/mimir
          EOF

          IMAGE=162230498103.dkr.ecr.eu-west-1.amazonaws.com/navitia-tyr-tyrworker
          TAG=dev
          docker build -t ${IMAGE}:${TAG} -f .mimirsbrunn-config/Dockerfile .mimirsbrunn-config
          docker push -t ${IMAGE}:${TAG}

  aws_release_images:
    runs-on: [self-hosted, build, shared_services]
    if: ${{ github.event.workflow_run.head_branch == 'release' }}
    name: AWS Release images
    steps:
      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v6
        with:
          strip_tag_prefix: v

      - name: Generate token
        id: app-token
        if: steps.branch-name.outputs.is_tag == 'true'
        uses: getsentry/action-github-app-token@v1
        with:
          app_id: ${{ secrets.AWS_TERRAFORM_WORKFLOW_APP_ID }}
          private_key: ${{ secrets.AWS_TERRAFORM_WORKFLOW_APP_PEM_KEY }}


      - name: Checkout mimirsbrunn-config
        if: steps.branch-name.outputs.is_tag == 'true'
        uses: actions/checkout@v3
        with:
          repository: hove-io/mimirsbrunn-config
          token: ${{ steps.app-token.outputs.token }}
          path: .mimirsbrunn-config

      - name: tyr-worker update
        if: steps.branch-name.outputs.is_tag == 'true'
        run: |
          cat << EOF > .mimirsbrunn-config/Dockerfile
          FROM navitia/tyr-worker
          COPY ./config /etc/mimir
          EOF

          IMAGE=162230498103.dkr.ecr.eu-west-1.amazonaws.com/navitia-tyr-tyrworker
          TAG=${{ steps.branch-name.outputs.tag }}
          docker build -t ${IMAGE}:${TAG} -f .mimirsbrunn-config/Dockerfile .mimirsbrunn-config
          docker push -t ${IMAGE}:${TAG}