name: Publish Docker Compose Images

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build Navitia Packages For Release", "Build Navitia Packages For Dev Multi Distributions"]
    branches: [release, dev]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get branch name
      run: echo ${{ github.event.ref }}
    - uses: actions/checkout@v3
      with:
        repository: hove-io/navitia-docker-compose
    - name: install httpie dependency
      run: sudo apt update && sudo apt install -y httpie
    - name: build, create and publish images for branch release
      if: ${{ github.event.workflow_run.head_branch == 'release' }}
      working-directory: builder_from_package
      run: ./build.sh -e push -o ${{secrets.access_token_github}} -t latest -b release -r -u ${{secrets.docker_user}} -p ${{secrets.docker_password}}
    - name: build, create and publish images for branch dev
      if: ${{ github.event.workflow_run.head_branch == 'dev' }}
      working-directory: builder_from_package
      run: ./build.sh -e push -o ${{secrets.access_token_github}} -t dev -b dev -r -u ${{secrets.docker_user}} -p ${{secrets.docker_password}}
    - name: slack notification (the job has failed)
      if: failure()
      run: |
          echo '{"text":":warning: Navitia Github Actions: publish_docker_compose_images failed ! (https://github.com/hove-io/navitia/actions?query=workflow%3A%22Publish+Docker+Compose+Images%22)"}' | http --json POST ${{secrets.SLACK_NAVITIA_TEAM_URL}}

