name: CI

on:
  push:
    branches:
      - dev
  pull_request:

jobs:

  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: checkout submodules
      shell: bash
      run: |
        sed -i 's,git\@github.com:\([^/]*\)/\(.*\).git,https://github.com/\1/\2,' .gitmodules
        git submodule update --init --recursive
    - name: check submodules
      run: ./source/scripts/check_submodules.sh
